# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Matt (Mateusz) Kutyba
email: hello@kutyba.it
description: IT Business Partner and Project Manager.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kutyba.it" # the base hostname & protocol for your site
AUTHOR: Matt Kutyba
github_username:  mkutyba
linkedin_username:  kutyba
logo: /assets/images/matt-kutyba.png
image: /assets/images/matt-kutyba.png
uaid: G-D7FZDT4FN6

# Build settings
markdown: kramdown

permalink:  /blog/:title.html

sass:
  style: compressed

plugins:
  - jekyll-relative-links
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/matt-kutyba.png

exclude: [vendor]