# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mateusz Kutyba - Full Stack Developer
email: m@kutyba.it
description: > # this means to ignore newlines until "baseurl:"
  Full Stack Developer for hire.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kutyba.it" # the base hostname & protocol for your site
twitter_username: kutybait
github_username:  mkutyba
linkedin_username:  kutyba
uaid: UA-4500350-12

# Build settings
markdown: kramdown

permalink:  /blog/:title.html

sass:
  style: compressed