# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mateusz Kutyba
email: m@kutyba.it
description: eCommerce consultant for hire.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kutyba.it" # the base hostname & protocol for your site
AUTHOR: Mateusz Kutyba
twitter_username: kutybait
github_username:  mkutyba
linkedin_username:  kutyba
logo: /assets/images/mateusz-kutyba.png
image: /assets/images/mateusz-kutyba.png
uaid: UA-4500350-12

# Build settings
markdown: kramdown

permalink:  /blog/:title.html

sass:
  style: compressed

gems:
  - jekyll-relative-links
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/mateusz-kutyba.png
